### PR TITLE
correcting headers in auth request

### PR DESCRIPTION
**Pull request by colins44**
got to manipulate the headers

### CODE REVIEW

**Comment by mynameisrufus** [comment]
This is a very good correction of headers :+1:

**Comment by colins44** [comment]
Thanks @mynameisrufus it was actually quite confusing as this is the exact same code that works within other services, yet a different version of node-fetch, the result of which was that calls to the auth service just hung

**Comment by mynameisrufus** [comment]
@colins44 very interesting, I think I have had the recently also but can't remember the reason why

**Comment by colins44** [comment]
@mynameisrufus we should keep eye out for this!

**Pull request merged**
